name: 'Check deadline'

on: 
  workflow_dispatch:
    inputs:
      assignment_name:
        description: 'Name of the assignment'
        required: true
      submitted_date:
        description: 'Date the assignment was submitted'
        required: true
      starting_points:
        description: 'Earned points before late penalties'
        default: 100
        required: true
        type: 'number'
      extension_hours:
        description: 'Amount of extension granted (in hours)'
        default: 0
        required: false
        type: 'number'

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      - name: Run action
        id: run-action
        uses: usf-cs272-fall2022/action-check-deadline@main
        with:
          assignment_name: ${{ inputs.assignment_name }}
          submitted_date:  ${{ inputs.submitted_date }}
          starting_points: ${{ inputs.starting_points }}
          extension_hours: ${{ inputs.extension_hours }}

      - name: Output results
        id: output-results
        run: |
          echo  "Submitted: ${{ steps.run-action.outputs.submitted_text }}"
          echo   "Deadline: ${{ steps.run-action.outputs.deadline_text }}"
          echo ""

          echo   "Interval: ${{ steps.run-action.outputs.late_interval }}"
          echo "Multiplier: ${{ steps.run-action.outputs.late_multiplier }}"
          echo    "Penalty: ${{ steps.run-action.outputs.late_percent }}% (${{ steps.run-action.outputs.late_points }} points)"

          echo ""
          echo      "Grade: ${{ steps.run-action.outputs.grade_points }} / ${{ steps.run-action.outputs.grade_possible }} (${{ steps.run-action.outputs.grade_percent }}%)"
